// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAteuL68MJqPOgQwkFWpQEMfkyWcxoR240',
    appId: '1:517857683625:web:85b4e95824722bd0ece1b8',
    messagingSenderId: '517857683625',
    projectId: 'zdpmanagement',
    authDomain: 'zdpmanagement.firebaseapp.com',
    storageBucket: 'zdpmanagement.firebasestorage.app',
    measurementId: 'G-JQEHJ3CE0K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtuY5paKm9r9yY6Cj4bKJYuXmcPUPVsVw',
    appId: '1:517857683625:android:07757c9edaedf79aece1b8',
    messagingSenderId: '517857683625',
    projectId: 'zdpmanagement',
    storageBucket: 'zdpmanagement.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArVMcw4CCY_5nZf1Yzx0eMPK0XShQx0VY',
    appId: '1:517857683625:ios:9bf766835499ee12ece1b8',
    messagingSenderId: '517857683625',
    projectId: 'zdpmanagement',
    storageBucket: 'zdpmanagement.firebasestorage.app',
    iosBundleId: 'com.example.contadorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArVMcw4CCY_5nZf1Yzx0eMPK0XShQx0VY',
    appId: '1:517857683625:ios:9bf766835499ee12ece1b8',
    messagingSenderId: '517857683625',
    projectId: 'zdpmanagement',
    storageBucket: 'zdpmanagement.firebasestorage.app',
    iosBundleId: 'com.example.contadorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAteuL68MJqPOgQwkFWpQEMfkyWcxoR240',
    appId: '1:517857683625:web:9954912ce4716403ece1b8',
    messagingSenderId: '517857683625',
    projectId: 'zdpmanagement',
    authDomain: 'zdpmanagement.firebaseapp.com',
    storageBucket: 'zdpmanagement.firebasestorage.app',
    measurementId: 'G-936K5QT7J5',
  );
}
